from setuptools import setup, find_packages

extra_packages = {
    "full": [
        "rpy2",
        "tpot",
        "anndata",
        "biopython",
        "dask",
        "numba",
        "imblearn",
        "leidenalg",
        "networkx",
        "opentsne",
        "plotly",
        "pynndescent",
        "scanpy",
        "scikit-learn",
        "statsmodels",
    ],
    "analysis": [
        "anndata",
        "biopython",
        "dask",
        "numba",
        "imblearn",
        "leidenalg",
        "networkx",
        "opentsne",
        "plotly",
        "pynndescent",
        "scanpy",
        "scikit-learn",
        "statsmodels",
    ]
}
setup(
    name="allcools",
    use_scm_version=True,
    setup_requires=["setuptools_scm"],
    author="Hanqing Liu",
    author_email="hanliu@salk.edu",
    description="Tool kit for single-cell methylome data analysis.",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/lhqing/ALLCools",
    license="MIT",
    classifiers=[
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
    ],
    packages=find_packages(exclude=("docs", "test")),
    package_data={"": ["*.meme", "*.csv"]},
    include_package_data=True,
    extras_require=extra_packages,
    install_requires=[
        "numpy",
        'matplotlib',
        "natsort",
        "pandas",
        "pybedtools",
        "pyBigWig",
        "pysam",
        'seaborn',
        "xarray",
        "pyyaml",
    ],
    entry_points={
        "console_scripts": ["allcools=ALLCools.__main__:main"],
    },
)
